build ubuntu all

diff --git a/.github/workflows/bulid_ubuntu_rocm.yml b/.github/workflows/bulid_ubuntu_rocm.yml
--- a/.github/workflows/bulid_ubuntu_rocm.yml
+++ b/.github/workflows/bulid_ubuntu_rocm.yml
@@ -9,12 +9,15 @@ env:
   gmxversion: "2024.4"
   gmxcompileto: /home/gmxfiles
   adcppto: /home/adcpp
-  # must be 5.7
   ROCM_PATH: /opt/rocm
 
 jobs:
   Ubuntu:
-    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        os_ver: [20.04, 22.04]
+
+    runs-on: ubuntu-${{matrix.os_ver}}
 
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
@@ -23,12 +26,23 @@ jobs:
 
       - name: Install ROCM
         run: |
+          # clean up space
+          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
+
           sudo apt update
-          wget -O amdgpu-install.deb http://repo.radeon.com/amdgpu-install/5.7/ubuntu/jammy/amdgpu-install_5.7.50700-1_all.deb
+          if [ "${{ matrix.os_ver }}" == "20.04" ]; then
+            export UBUNTU_CODENAME="focal";
+          elif [ "${{ matrix.os_ver }}" == "22.04" ]; then
+            export UBUNTU_CODENAME="jammy";
+          else
+            echo "Unsupported Ubuntu version"; exit 1;
+          fi
+          wget -O amdgpu-install.deb http://repo.radeon.com/amdgpu-install/5.7/ubuntu/${UBUNTU_CODENAME}/amdgpu-install_5.7.50700-1_all.deb
           sudo apt install ./amdgpu-install.deb -y
           amdgpu-install -y --usecase=rocm,hiplibsdk,graphics --no-dkms --no-32
           # test
           #rocminfo
+
       - name: Install Adaptive
         run: |
           sudo apt install libboost-all-dev -y
